networks:
  proxy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16



services:
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      proxy:
        ipv4_address: 172.20.0.10
    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
      - './caddy/data/:/data/'
      - './caddy/config/:/config/'

  car_fi:
    container_name: car_fi
    image: my_car_fi
    restart: unless-stopped
    build:
      context: .
      dockerfile: car.fi.dockerfile
    networks:
      proxy:
        ipv4_address: 172.20.0.100
    command: bash -c "osrm-routed --algorithm mld finland-latest.osrm"

  bike_fi:
    container_name: bike_fi
    image: my_bike_fi
    restart: unless-stopped
    build:
      context: .
      dockerfile: bike.fi.dockerfile
    networks:
      proxy:
        ipv4_address: 172.20.0.101
    command: bash -c "osrm-routed --algorithm mld finland-latest.osrm"

  foot_fi:
    container_name: foot_fi
    image: my_foot_fi
    restart: unless-stopped
    build:
      context: .
      dockerfile: foot.fi.dockerfile
    networks:
      proxy:
        ipv4_address: 172.20.0.102
    command: bash -c "osrm-routed --algorithm mld finland-latest.osrm"

  finland:
    container_name: finland
    image: wiktorn/overpass-api
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.0.40
    volumes:
      - './overpass/finland/:/db/'
    environment:
      OVERPASS_MODE: init
      OVERPASS_META: yes
      OVERPASS_PLANET_URL: https://download.geofabrik.de/europe/finland-latest.osm.bz2
      OVERPASS_DIFF_URL: https://download.geofabrik.de/europe/finland-updates/
      OVERPASS_COMPRESSION: gz
      OVERPASS_RULES_LOAD: 100

  germany:
    container_name: germany
    image: wiktorn/overpass-api
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.0.50
    volumes:
      - './overpass/germany/:/db/'
    environment:
      OVERPASS_MODE: init
      OVERPASS_META: yes
      OVERPASS_PLANET_URL: https://download.geofabrik.de/europe/germany-latest.osm.bz2
      OVERPASS_DIFF_URL: https://download.geofabrik.de/europe/germany-updates/
      OVERPASS_COMPRESSION: gz
      OVERPASS_RULES_LOAD: 100

  netherlands:
    container_name: netherlands
    image: wiktorn/overpass-api
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.0.70
    volumes:
      - './overpass/netherlands/:/db/'
    environment:
      OVERPASS_MODE: init
      OVERPASS_META: yes
      OVERPASS_PLANET_URL: https://download.geofabrik.de/europe/netherlands-latest.osm.bz2
      OVERPASS_DIFF_URL: https://download.geofabrik.de/europe/netherlands-updates/
      OVERPASS_COMPRESSION: gz
      OVERPASS_RULES_LOAD: 100

  singapore:
    container_name: singapore
    image: wiktorn/overpass-api
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 172.20.0.80
    volumes:
      - './overpass/singapore/:/db/'
    environment:
      OVERPASS_MODE: init
      OVERPASS_META: yes
      OVERPASS_PLANET_URL: https://download.geofabrik.de/asia/malaysia-singapore-brunei-latest.osm.bz2
      OVERPASS_DIFF_URL: https://download.geofabrik.de/asia/malaysia-singapore-brunei-updates/
      OVERPASS_COMPRESSION: gz
      OVERPASS_RULES_LOAD: 100
