networks:
    proxy:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
    db:
        driver: bridge
        ipam:
            config:
                - subnet: 172.30.0.0/16



services:
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      proxy:
        ipv4_address: 172.20.0.10
    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile:ro'
      - './caddy/data/:/data/'
      - './caddy/config/:/config/'
  
  pg:
    container_name: postgres
    image: postgis/postgis
    restart: unless-stopped
    networks:
      db:
        ipv4_address: 172.30.0.10
    volumes:
      - './postgres/data/:/var/lib/postgresql/data/'
    environment:
      POSTGRES_USER: 'Streusels'
      POSTGRES_PASSWORD: 'Mcytzhj@3jN95E$4%qAk4eHH9$4Ta#7e2WuattHB9MVosxDHgf'
      PGDATA: '/var/lib/postgresql/data/pgdata/'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    networks:
      db:
        ipv4_address: 172.30.0.20
      proxy:
        ipv4_address: 172.20.0.20
    environment:
      PGADMIN_DEFAULT_EMAIL: 'le.wimbes@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'Mcytzhj@3jN95E$4%qAk4eHH9$4Ta#7e2WuattHB9MVosxDHgf'
      PGDATA: '/var/lib/postgresql/data/pgdata/'
